version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./seomigratorpy:/seomigratorpy
      - static_volume:/seomigratorpy/static
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - static_volume:/home/app/web/static
    ports:
      - "80:80"
      # - "8000:8000"
    depends_on:
      - web
  db:
    image: mariadb:10.6.16
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3300:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=seomigratorpy
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=secret
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 8080:80
    depends_on:
      - db

volumes:
  mariadb_data:
  static_volume:

