# Generated by Django 4.2.7 on 2023-11-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0002_rename_domaine_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
