# Generated by Django 4.2.7 on 2023-11-28 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0007_alter_url_last_indexed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrator.url')),
            ],
        ),
    ]
