# Generated by Django 4.2.7 on 2023-11-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0010_alter_queue_url_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='time_to_first_bite',
            field=models.IntegerField(null=True),
        ),
    ]
