# Generated by Django 4.2.7 on 2023-11-30 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0013_alter_queue_url_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='url_id',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='queue',
            old_name='url_id',
            new_name='url',
        ),
    ]
