# Generated by Django 4.2.7 on 2023-11-30 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0021_alter_url_page_id_alter_url_domain_alter_url_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='queue',
            name='url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='migrator.url'),
        ),
    ]
