# Generated by Django 4.2.7 on 2023-12-01 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('url', models.URLField(unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=2083, null=True)),
                ('http_status', models.IntegerField(null=True)),
                ('protocol', models.CharField(default='https', max_length=255)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_indexed', models.DateTimeField(null=True)),
                ('time_to_first_bite', models.FloatField(null=True)),
                ('Page_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='migrator.page')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='migrator.domain')),
                ('subdomain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='migrator.subdomain')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='migrator.url')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='main_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_url', to='migrator.url'),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('queryParam', models.CharField(max_length=255)),
                ('fragment', models.CharField(max_length=255)),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrator.page')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrator.url')),
            ],
        ),
    ]
