# Generated by Django 4.2.7 on 2023-11-28 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0003_alter_url_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='Domain_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='migrator.domain'),
        ),
        migrations.AddField(
            model_name='url',
            name='Page_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='migrator.page'),
        ),
        migrations.AddField(
            model_name='url',
            name='Subdomain_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='migrator.subdomain'),
        ),
        migrations.AddField(
            model_name='url',
            name='http_status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='path',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Url_meta',
        ),
    ]
