# Generated by Django 4.2.7 on 2023-11-28 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0005_remove_link_protocol_url_protocol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='last_indexed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='protocol',
            field=models.CharField(default='https', max_length=255),
        ),
    ]
