# Generated by Django 4.2.7 on 2023-11-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0006_url_first_seen_url_last_indexed_alter_url_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='last_indexed',
            field=models.DateTimeField(null=True),
        ),
    ]
