# Generated by Django 4.2.7 on 2023-11-28 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0008_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='Domain_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrator.domain'),
        ),
    ]
