# Generated by Django 4.2.7 on 2023-11-28 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0009_alter_url_domain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='url_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrator.url', unique=True),
        ),
    ]
