# Generated by Django 4.2.7 on 2023-11-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0011_url_time_to_first_bite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='time_to_first_bite',
            field=models.FloatField(null=True),
        ),
    ]
