# Generated by Django 4.2.7 on 2023-11-30 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0012_alter_url_time_to_first_bite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='url_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='migrator.url'),
        ),
    ]
