# Generated by Django 4.2.7 on 2023-11-30 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0014_rename_url_id_link_url_rename_url_id_queue_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='Subdomain_id',
            new_name='subdomain',
        ),
    ]
