# Generated by Django 4.2.7 on 2023-11-30 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0015_rename_subdomain_id_url_subdomain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='Domain_id',
            new_name='domain',
        ),
    ]
