# Generated by Django 4.2.7 on 2023-11-30 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0016_rename_domain_id_url_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrator.url', unique=True),
        ),
    ]
