# Generated by Django 4.2.7 on 2023-11-30 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0018_alter_page_url_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='url_id',
        ),
        migrations.AddField(
            model_name='page',
            name='main_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_url', to='migrator.url'),
        ),
    ]
