# Generated by Django 4.2.7 on 2023-11-30 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0019_remove_page_url_id_page_main_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='id',
        ),
        migrations.AlterField(
            model_name='queue',
            name='url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='queue', serialize=False, to='migrator.url'),
        ),
    ]
