# Generated by Django 4.2.7 on 2023-11-30 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0020_remove_queue_id_alter_queue_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='Page_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='migrator.page'),
        ),
        migrations.AlterField(
            model_name='url',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='migrator.domain'),
        ),
        migrations.AlterField(
            model_name='url',
            name='path',
            field=models.CharField(max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='subdomain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='migrator.subdomain'),
        ),
    ]
